export const solutionDescriptions = {
  antimony: {
    zh: '原矿经粗破后筛分，大块矿石手选出块状锑精矿，其余进入中破；中破料与细料汇合后跳汰重选，尾矿经磨矿分级与浮选，最后通过摇床回收氧化锑精矿。',
    en: 'Raw ore is coarsely crushed and screened. Lump ore is hand-sorted, while the remaining material is jigged for gravity separation. Gravity tailings are ground, classified, and floated, with shaking-table scavenging recovering oxide antimony concentrate.',
    es: 'El mineral en bruto se tritura grueso y se tamiza. El mineral en terrones se selecciona manualmente, mientras que el material restante se somete a jigging para separacion gravitacional. Los relaves gravitacionales se muelen, clasifican y flotan, con la recuperacion de concentrado de antimonio oxidado por mesas vibratorias.',
    ru: 'Руда подвергается крупному дроблению и грохочению. Крупные куски руды отбираются вручную для получения сурьмяного концентрата, остальной материал поступает на среднее дробление; после отсадки для гравитационного обогащения, хвосты измельчаются, классифицируются и флотируются, с извлечением оксидного сурьмяного концентрата на концентрационных столах.',
  },
  gold: {
    zh: '含金矿物经碎磨、筛分和浓缩后进入氰化浸出；浸出矿浆通过炭吸附、解吸、电积和熔炼产出金锭，活性炭再生循环使用，尾矿水经脱水回用。',
    en: 'Gold-bearing material is crushed, ground, screened, and thickened before cyanidation. Carbon adsorption, elution, electrowinning, and smelting produce gold ingots, while regenerated carbon and dewatered tailing water are recycled.',
    es: 'El material que contiene oro se tritura, muele, tamiza y espesa antes de la cianuracion. La adsorcion de carbon, elucion, electroobtencion y fundicion producen lingotes de oro, mientras que el carbon regenerado y el agua de relaves espesada se reciclan.',
    ru: 'Золотосодержащий материал дробится, измельчается, грохотится и сгущается перед цианированием. Адсорбция на уголь, десорбция, электроосаждение и плавка дают золотые слитки, а регенерированный уголь и обезвоженная хвостовая вода возвращаются в цикл.',
  },
  'manganese-iron': {
    zh: '原矿经两段破碎后进入回转窑还原焙烧，冷却后闭路磨矿分级；矿浆先经弱磁选回收铁精矿，尾矿再经强磁选获得锰精矿，实现锰铁高效分离。',
    en: 'The ore is crushed in two stages and reduction-roasted in a rotary kiln. After cooling and closed-circuit grinding, LIMS recovers iron concentrate and HIMS treats the tailings to recover manganese concentrate.',
    es: 'El mineral se tritura en dos etapas y se tuesta de reduccion en un horno rotativo. Despues del enfriamiento y molienda en circuito cerrado, LIMS recupera el concentrado de hierro y HIMS trata los relaves para recuperar concentrado de manganeso.',
    ru: 'Руда дробится в две стадии и восстановительно обжигается во вращающейся печи. После охлаждения и замкнутого цикла измельчения и классификации слабомагнитная сепарация (LIMS) извлекает железный концентрат, а сильномагнитная сепарация (HIMS) обрабатывает хвосты для получения марганцевого концентрата.',
  },
  manganese: {
    zh: '锰矿经破碎磨细后先进行物理选矿，锰尾矿再经焙烧浸出，并通过沉淀除铜、除铁及沉淀钴镍，最终由纯化母液电解生产高纯度金属锰。',
    en: 'Manganese ore is crushed and ground for physical beneficiating. Tailings undergo roasting and leaching, followed by copper, iron, cobalt, and nickel removal, before electrowinning produces high-purity manganese metal.',
    es: 'El mineral de manganeso se tritura y muele para beneficio fisico. Los relaves se tuestan y lixivian, seguido de la remocion de cobre, hierro, cobalto y niquel, antes de que la electroobtencion produzca manganeso metalico de alta pureza.',
    ru: 'Марганцевая руда дробится и измельчается для физического обогащения. Хвосты подвергаются обжигу и выщелачиванию с последующим удалением меди, железа, кобальта и никеля, после чего электроосаждение производит высокочистый марганцевый металл.',
  },
  bauxite: {
    zh: '铝土矿磨矿后采用高堰式与沉降式分级，粗粒部分直接回收，细粒部分调浆后进入浮选系统，通过多次精选与扫选去除硅酸盐杂质，获得高铝硅比精矿。',
    en: 'Bauxite is ground and classified with high-weir and submerged classifiers. Coarse material is recovered directly, while fines are conditioned and floated through multi-stage cleaning and scavenging to reject silicate impurities.',
    es: 'La bauxita se muele y clasifica con clasificadores de vertedero alto y sumergidos. El material grueso se recupera directamente, mientras que los finos se acondicionan y flotan a traves de limpiadoras y depuradoras multietapa para rechazar impurezas de silicato.',
    ru: 'Боксит измельчается и классифицируется с помощью высокопороговых и подводных классификаторов. Крупный материал возвращается напрямую, а мелкие фракции кондиционируются и флотируются через многоступенчатую очистку и перечистку для удаления силикатных примесей.',
  },
  silica: {
    zh: '原砂经擦洗、脱泥和螺旋分级后进入含铁矿物浮选，去除重矿物；随后再次分级调浆，通过硅砂浮选实现长石与硅砂分离，分别获得两种精矿。',
    en: 'Raw sand is scrubbed, deslimed, and classified before iron-bearing mineral flotation removes heavy minerals. A second classification and conditioning stage prepares the feed for silica flotation, separating feldspar and silica sand concentrates.',
    es: 'La arena en bruto se lava, deslamifica y clasifica antes de la flotacion de minerales ferricos que elimina los minerales pesados. Una segunda etapa de clasificacion y acondicionamiento prepara la alimentacion para la flotacion de silice, separando concentrados de feldespato y arena de silice.',
    ru: 'Исходный песок подвергается скрабингу, обесшламливанию и спиральной классификации перед флотацией железистых минералов для удаления тяжёлых минералов. Вторая стадия классификации и кондиционирования готовит питание для флотации кварцевого песка, разделяя полевой шпат и кварцевый песок.',
  },
  ilmenite: {
    zh: '原矿经破碎、磨矿分级后磁选回收磁铁精矿；磁选尾矿进入螺旋溜槽重选，再结合电磁选与钛粗选、扫选、精选流程回收钛铁矿精矿。',
    en: 'After crushing and grinding-classification, magnetic separation recovers magnetite. The tailings pass through spiral gravity concentration and combined magnetic or electrostatic separation with titanium roughing, scavenging, and cleaning.',
    es: 'Despues de la trituracion y clasificacion por molienda, la separacion magnetica recupera magnetita. Los relaves pasan por concentracion gravitacional en espiral y separacion magnetica o electrostatica combinada con depuracion, barrido y limpieza de titanio.',
    ru: 'После дробления и измельчения с классификацией магнитная сепарация извлекает магнетитовый концентрат. Хвосты магнитной сепарации проходят гравитационное обогащение на спиральных шлюзах в сочетании с электромагнитной сепарацией и черновой флотацией, перечисткой и очисткой титана для извлечения ильменитового концентрата.',
  },
  copper: {
    zh: '原矿经磨矿分级与闭路再磨后进入浮选系统，采用一粗、二精、三扫流程，中矿梯级返回循环，最终获得高品位铜精矿，尾矿作为最终尾矿排出。',
    en: 'The ore is ground, classified, and re-ground in a closed circuit before flotation. A conventional one-rougher, two-cleaner, three-scavenger flowsheet with staged middlings return produces high-grade copper concentrate.',
    es: 'El mineral se muele, clasifica y remuele en un circuito cerrado antes de la flotacion. Un diagrama de flujo convencional de un rougher, dos limpiadoras, tres depuradoras con retorno escalonado de medios produce concentrado de cobre de alta ley.',
    ru: 'Руда измельчается, классифицируется и домалывается в замкнутом цикле перед флотацией. Классическая схема с одним черновым, двумя очистительными и тремя перечистными циклами с градуированным возвратом промпродуктов обеспечивает получение медного концентрата высокого качества.',
  },
  'alluvial-tin': {
    zh: '砂锡矿利用锡石高密度特性，经过溜槽、滚筒筛脱泥分级后，筛下物经给料机均匀给入跳汰机粗选，粗精矿再经摇床精选产出高品位锡精矿。',
    en: 'Taking advantage of cassiterite density, the ore is deslimed and classified with sluices and trommel screens. Undersize is fed to jigs for roughing, then to shaking tables for cleaning and high-grade tin recovery.',
    es: 'Aprovechando la densidad de la casiterita, el mineral se deslamifica y clasifica con canales y tamices rotativos. El undersize se alimenta a jigs para depuracion gruesa, luego a mesas vibratorias para limpieza y recuperacion de estano de alta ley.',
    ru: 'Используя высокую плотность касситерита, руда обесшламливается и классифицируется с помощью шлюзов и барабанных грохотов. Мелкая фракция равномерно подаётся на отсадочные машины для черновой флотации, а черновой концентрат очищается на концентрационных столах для получения высококачественного оловянного концентрата.',
  },
  'alluvial-gold': {
    zh: '矿砂经碎解和分级后弃去大块砾石，细砂进入重选粗选；重砂经精选获得砂金精矿，粗选尾矿再分级并扫选，进一步回收细粒金。',
    en: 'Gravel is disintegrated and screened to discard oversize. Fine sand undergoes gravity roughing and heavy-sand cleaning, while roughing tailings are classified and scavenged to recover additional fine gold.',
    es: 'La grava se desintegra y tamiza para descartar el oversize. La arena fina se somete a depuracion gravitacional y limpieza de arena pesada, mientras que los relaves de depuracion se clasifican y depuran para recuperar oro fino adicional.',
    ru: 'Гравий дезинтегрируется и грохотится для удаления крупной фракции. Мелкий песок проходит гравитационную черновую флотацию и очистку тяжёлых песков, а хвосты черновой флотации дополнительно классифицируются и перечищаются для извлечения мелкого золота.',
  },
  'iron-ore': {
    zh: '原矿经棒磨、多段球磨和闭路分级后脱水进入弱磁选，直接回收铁精矿；磁选尾矿再经萤石与稀土浮选、磁选及脱水，实现铁、萤石与稀土综合回收。',
    en: 'Rod and multi-stage ball milling produce a finely classified feed for LIMS iron recovery. The tailings enter fluorite and rare-earth flotation and magnetic separation circuits, enabling comprehensive recovery of iron, fluorite, and REEs.',
    es: 'La molienda con barras y bolas multietapa produce una alimentacion finamente clasificada para la recuperacion de hierro por LIMS. Los relaves entran en circuitos de flotacion de fluorita y tierras raras y separacion magnetica, permitiendo la recuperacion integral de hierro, fluorita y TRE.',
    ru: 'Стержневое и многостадиальное шаровое измельчение обеспечивает тонкую классификацию для извлечения железа методом слабомагнитной сепарации (LIMS). Хвосты поступают на флотацию флюорита и редкоземельных элементов и магнитную сепарацию, обеспечивая комплексное извлечение железа, флюорита и РЗЭ.',
  },
  'lead-zinc': {
    zh: '原矿经两段破碎、磨矿分级和调浆后，采用先铅后锌的优先浮选流程，分别经过粗选、三段精选和三段扫选获得铅精矿与锌精矿。',
    en: 'After two-stage crushing, grinding, classification, and conditioning, a lead-first preferential flotation route uses roughing, three cleaning stages, and three scavenging stages to produce lead and zinc concentrates.',
    es: 'Despues de la trituracion de dos etapas, molienda, clasificacion y acondicionamiento, una ruta de flotacion preferencial de plomo primero utiliza depuracion, tres etapas de limpieza y tres etapas de depuracion para producir concentrados de plomo y zinc.',
    ru: 'После двухстадиального дробления, измельчения, классификации и кондиционирования применяется приоритетная флотация свинца с последующим цинком: черновая флотация, три стадии очистки и три стадии перечистки обеспечивают получение свинцового и цинкового концентратов.',
  },
  fluorite: {
    zh: '原矿经破碎筛分后，粗粒级通过重介质选矿抛尾；细粒级磨矿调浆后依次进行铅、锌浮选，最终通过萤石粗选与三段精选、过滤、干燥和分级获得高纯萤石精矿。',
    en: 'After crushing and screening, coarse material is rejected by dense-medium separation. Fines are ground and conditioned for lead and zinc flotation, followed by fluorite roughing, three-stage cleaning, filtration, drying, and air classification.',
    es: 'Despues de la trituracion y tamizado, el material grueso se rechaza por separacion de medio denso. Los finos se muelen y acondicionan para flotacion de plomo y zinc, seguido de depuracion gruesa de fluorita, limpieza de tres etapas, filtracion, secado y clasificacion por aire.',
    ru: 'После дробления и грохочения крупная фракция отбрасывается тяжёлосредной сепарацией; мелкая фракция измельчается и кондиционируется для флотации свинца и цинка, затем следует черновая флотация флюорита, трёхстадиальная очистка, фильтрация, сушка и воздушная классификация для получения высокочистого флюоритового концентрата.',
  },
} as const
